# Generated by Django 2.1.4 on 2019-02-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_field',
            new_name='image',
        ),
    ]
